"""
This type stub file was generated by pyright.
"""

class EdinetExceptions(Exception):
    """Edinetの例外の基底クラス"""
    ...


class ResponseNot200(EdinetExceptions):
    """レスポンスが200ではない時に投げられる"""
    ...


class BadRequest(ResponseNot200):
    """400エラー、リクエストパラメータになにか問題があると投げられる"""
    ...


class InvalidAPIKey(ResponseNot200):
    """401エラー、APIキーが無効だと投げられる"""
    ...


class ResourceNotFound(ResponseNot200):
    """404エラー、データが無いと投げられる"""
    ...


class InternalServerError(ResponseNot200):
    """500エラー、鯖側がおかしいと投げられる"""
    ...


