"""
This type stub file was generated by pyright.
"""

import datetime
from typing import Literal, Union, overload

from edinet.enums.response import GetDocumentResponse, GetDocumentResponseWithDocs

__all__ = ["Edinet"]

class Edinet:
    def __init__(self, token: str) -> None:
        """
        Edinet APIのラッパー

        Parameters
        ----------
        token: str
            APIのキー
        """
        ...

    @overload
    def get_document_list(
        self, date: datetime.datetime, withdocs: Literal[False]
    ) -> GetDocumentResponse: ...
    @overload
    def get_document_list(
        self, date: datetime.datetime, withdocs: Literal[True]
    ) -> GetDocumentResponseWithDocs: ...
    @overload
    def get_document_list(self, date: datetime.datetime) -> GetDocumentResponse: ...
    def get_document_list(
        self, date: datetime.datetime, withdocs: bool = ...
    ) -> Union[GetDocumentResponse, GetDocumentResponseWithDocs]:
        """
        `documents.json`エンドポイントのラッパー

        Parameters
        ----------
        date: datetime.datetime
            `datetime.datetime`オブジェクト、年月日の指定。
        withdocs: :obj:`bool`, default False
            提出書類一覧を含めるか、デフォルトは含めない。
        """
        ...

    def get_document(self, docId: str, type: Literal[1, 2, 3, 4, 5]) -> bytes:
        """
        ドキュメントの取得

        Parameters
        ----------
        docId: str
            書類管理番号
        type: Literal[1, 2, 3, 4, 5]
            - 1: 提出本文書及び監査報告書、XBRLを取得
            - 2: PDFを取得
            - 3: 代替書面・添付文書を取得
            - 4: 英文ファイルを取得
            - 5: CSVを取得
        """
        ...
